### PR TITLE
Fix brew style issues

### LINKED ISSUE #11: Installs on Apple Silicon failing
Though the tools run fine by way of Rosetta 2, the Homebrew tap is now failing with this message:

```bash
$ brew tap grafana/grafana                                                                                                      100% 
Updating Homebrew...
To restore the stashed changes to /opt/homebrew, run:
  cd /opt/homebrew && git stash pop
==> Tapping grafana/grafana
Cloning into '/opt/homebrew/Library/Taps/grafana/homebrew-grafana'...
remote: Enumerating objects: 136, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 136 (delta 23), reused 2 (delta 1), pack-reused 95
Receiving objects: 100% (136/136), 26.88 KiB | 1.58 MiB/s, done.
Resolving deltas: 100% (78/78), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/grafana/homebrew-grafana/cortextool.rb
formulae require at least a URL
Warning: Calling `cellar` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the grafana/grafana tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/grafana/homebrew-grafana/grafana.rb:12

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the grafana/grafana tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/grafana/homebrew-grafana/grafana.rb:13

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the grafana/grafana tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/grafana/homebrew-grafana/grafana.rb:14

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the grafana/grafana tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/grafana/homebrew-grafana/grafana.rb:15

Error: Cannot tap grafana/grafana: invalid syntax in tap!
```

I found this after having used the tap previously and then having to debug why I frequently got the error `Error: formulae require at least a URL`.

### PR DESCRIPTION
**Pull request by zoltanbedi**
I've just run the `brew style --fix`

Probably fixes #11

### CODE REVIEW

**Comment by genebean** [comment]
I don't think this will fully fix it due to lines like this without a corresponding line for non-Intel:
https://github.com/grafana/homebrew-grafana/blob/cdd6b9e850bc15ed0d4e98b7005040e9b1ea4df9/cortextool.rb#L11

**Comment by zoltanbedi** [comment]
Oh I see, yes you are right this just make the warnings go away but wont fix your problem. Maybe @grafana-support  or @inf0rmer can help with that?

**Comment by gotjosh** [comment]
A head's up that I have merged https://github.com/grafana/homebrew-grafana/pull/14 which should supersed this PR.

**Comment by zoltanbedi** [comment]
Awesome! Thanks @gotjosh 😄

**Pull request closed without merging**
